name: Markdownlint

on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Use Node.js
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 12.x
    - name: Run Markdownlint
      run: |
        npm i -g markdownlint-cli
        markdownlint "**/*.md"
